language: java

dist: trusty

services:
  - openjdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build -s

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - markus.oley@googlemail.com
